events {}

http {
  upstream api_servers {
    server api:8000;      
  }

  server {
    listen 80;

    client_max_body_size 50M;   # максимальный размер загружаемых файлов

    location / {
      proxy_pass http://api_servers;
    }
  }
}
